DROP TABLE IF EXISTS TBL_CLIENTS;
  
CREATE TABLE TBL_CLIENTS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50),
  address VARCHAR(250)
);


DROP TABLE IF EXISTS TBL_METERS;
  
CREATE TABLE TBL_METER_MEASUREMENTS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  client_id INT,
  date DATE,
  value INT,
  CONSTRAINT client_id FOREIGN KEY (client_id) REFERENCES TBL_CLIENTS (id)
);
